// Mock generated by https://www.mockaroo.com/

const mockDocument = [
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e7500001e",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e7500001f",
    },
    amount: "$9.31",
    category: "home",
    notes:
      "eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus",
    createdAt: "5/16/2020",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000020",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000021",
    },
    amount: "$7.85",
    category: "home",
    notes:
      "magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
    createdAt: "3/23/2020",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000022",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000023",
    },
    amount: "$3.58",
    category: "communications",
    notes:
      "adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis",
    createdAt: "3/3/2020",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000024",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000025",
    },
    amount: "$1.75",
    category: "communications",
    notes:
      "volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in",
    createdAt: "1/23/2020",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000026",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000027",
    },
    amount: "$3.19",
    category: "taxi",
    notes:
      "quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac",
    createdAt: "9/25/2019",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000028",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000029",
    },
    amount: "$2.97",
    category: "taxi",
    notes:
      "luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec",
    createdAt: "3/20/2020",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e7500002a",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e7500002b",
    },
    amount: "$8.25",
    category: "entertainment",
    notes:
      "vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla",
    createdAt: "7/23/2019",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e7500002c",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e7500002d",
    },
    amount: "$1.16",
    category: "entertainment",
    notes:
      "vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit",
    createdAt: "11/21/2019",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e7500002e",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e7500002f",
    },
    amount: "$5.94",
    category: "entertainment",
    notes:
      "accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas",
    createdAt: "7/8/2019",
  },
  {
    _id: {
      $oid: "5ed4a28cfc13ae3e75000030",
    },
    userId: {
      $oid: "5ed4a28cfc13ae3e75000031",
    },
    amount: "$4.84",
    category: "pets",
    notes:
      "venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in",
    createdAt: "11/17/2019",
  },
];

module.exports = {
  mockDocument,
};
